spring:

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/actor?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: zhouzhanfu053x

  jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update

